import type { MotionStudy } from './types';

// Manually authored launch-film study. Source: Todoist's public desktop Quick Add
// demonstration, preserved in .local/launch-todoist-sourcepack-20261003.
// HTML/SVG recreation only; no source screenshot pixels are used in this film.
const icon = (name:string) => {
  const paths:Record<string,string>={
    inbox:'<path d="M4 4h16v16H4zM4 14h5l2 3h2l2-3h5"/>',
    date:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4m8-4v4M4 10h16m-11 4h3"/>',
    flag:'<path d="M5 21V3m0 1c5-4 9 4 15 0v11c-6 4-10-4-15 0"/>',
    plus:'<path d="M12 5v14M5 12h14"/>',
    arrow:'<path d="M12 20V4M5 11l7-7 7 7"/>',
    attach:'<path d="M8 16l8-8a3 3 0 00-4-4L3 13a5 5 0 007 7l10-10M7 16l8-8"/>',
    label:'<path d="M3 3h9l9 9-9 9-9-9z"/><circle cx="8" cy="8" r="1"/>',
    target:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M12 12l9-9"/>',
    chevron:'<path d="M9 5l7 7-7 7"/>',
    close:'<path d="M6 6l12 12M6 18L18 6"/>',
  };
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.plus}</svg>`;
};
const mark='<svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><rect width="64" height="64" rx="14" fill="currentColor"/><g stroke="var(--mark-lines,#fff)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"><path d="M15 19l10 6 26-15M15 31l10 6 26-15M15 43l10 6 26-15"/></g></svg>';
const cursor='<svg viewBox="0 0 48 60" aria-hidden="true"><path d="M5 3L42 32L26 34L37 50L29 56L19 39L8 51Z" fill="#292421" stroke="#fff" stroke-width="3" stroke-linejoin="round"/></svg>';

export const todoistStudy:MotionStudy={
 id:'launch-todoist',title:'Todoist — a little more headspace',width:1920,height:1080,fps:30,durationFrames:720,
 reference:{path:'',startSeconds:0,durationSeconds:24},
 html:`
 <div id="td-paper"></div><div id="td-binding"></div>
 <div id="td-hook"><div class="td-eyebrow">FOR INDEPENDENT PROFESSIONALS</div><h1><span id="td-too">Too much</span><span id="td-mind">on your mind<span class="td-red">?</span></span></h1><div class="td-hook-rule"></div><div class="td-hook-sub">Clients. Life. Everything between.</div></div>
 <div id="td-thoughts">${['Send proposal','Meet with Ada','Book the dentist'].map((text,i)=>`<div class="td-thought" id="td-thought-${i}"><span class="td-paper-hole"></span><span class="td-thought-title">${text}</span><span class="td-thought-index">0${i+1}</span></div>`).join('')}</div>
 <div id="td-app-camera"><div id="td-app">
   <div class="td-chrome"><div class="td-traffic"><i></i><i></i><i></i></div><div class="td-sidebar-icon"></div><span class="td-nav-chevron">‹</span><span class="td-nav-chevron">›</span><div class="td-app-wordmark">${mark}<span>todoist</span></div><span class="td-chrome-more">···</span></div>
   <div id="td-inbox-heading">Inbox</div>
   <div id="td-inbox-add">${icon('plus')}<span>Add task</span></div>
   <div class="td-section" id="td-work-section">${icon('chevron')}<b>Work</b><span>1</span><i>···</i></div>
   <div class="td-section" id="td-personal-section">${icon('chevron')}<b>Personal</b><span>4</span><i>···</i></div>
   <div id="td-app-dimmer"></div>
   <div id="td-composer"><div class="td-input"><span id="td-typed-task"></span><span id="td-typed-date"></span><span id="td-typed-priority"></span><i id="td-caret"></i><span id="td-placeholder">Task name</span></div>
     <div class="td-controls"><span class="td-tool-plus">${icon('plus')}</span><span class="td-chip">${icon('inbox')}Inbox</span><span class="td-chip" id="td-date-chip">${icon('date')}<span id="td-date-value">Date</span><span class="td-chip-dismiss" id="td-date-dismiss">×</span></span><span class="td-chip" id="td-priority-chip">${icon('flag')}<span id="td-priority-value">Priority</span><span class="td-chip-dismiss" id="td-priority-dismiss">×</span></span><span class="td-chip">${icon('target')}Deadline</span><span class="td-chip">${icon('label')}Labels</span></div>
     <div class="td-attachment">${icon('attach')}Attachment</div><div id="td-send-close">${icon('close')}</div><div id="td-send">${icon('arrow')}</div>
   </div>
   <div id="td-result-row"><div class="td-task-circle"></div><div class="td-task-title">Meet with Ada</div><div class="td-task-date">${icon('date')}<span>Tomorrow 14:00</span></div></div>
   <div id="td-toast">Task added to <u>Inbox</u><span>Open</span>${icon('close')}</div>
 </div></div>
 <div id="td-proof-label"><span>TODOIST</span><b>Thought → task</b></div>
 <div id="td-typing-caption"><span class="td-caption-kicker">QUICK ADD</span><div>Just write it.</div></div>
 <div id="td-date-caption"><span class="td-caption-kicker">NATURAL LANGUAGE</span><div>Dates, understood<span>.</span></div></div>
 <div id="td-submit-caption"><div>Give it a place.</div><span>ADD TO INBOX</span></div>
 <div id="td-cursor">${cursor}</div><div id="td-click-ring"></div>
 <div id="td-transfer"><span class="td-task-circle"></span><b>Meet with Ada</b><small>${icon('date')}Tomorrow 14:00</small></div>
 <div id="td-result-copy"><div class="td-eyebrow">CAPTURED. DATED. SAVED.</div><div class="td-result-line" id="td-result-line-0">One less</div><div class="td-result-line" id="td-result-line-1">thing to</div><div class="td-result-line td-red" id="td-result-line-2">remember.</div><div class="td-result-copy-line"></div></div>
 <div id="td-payoff"><div class="td-payoff-over">WORK & LIFE, IN ORDER</div><div class="td-payoff-words"><span id="td-space-a">A little more</span><span id="td-space-b">headspace<span class="td-red">.</span></span></div><div id="td-paper-line"></div><div id="td-payoff-task"><span class="td-task-circle"></span><b>Meet with Ada</b><span>Tomorrow 14:00</span></div></div>
 <div id="td-red-curtain"></div>
 <div id="td-end"><div id="td-end-mark">${mark}</div><div id="td-end-name">todoist</div><div id="td-end-line"></div><div id="td-end-tag">Make room for what matters.</div><div id="td-end-cta"><span>Start for free</span><svg viewBox="0 0 42 42"><path d="M7 21h28M24 10l11 11-11 11" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div id="td-end-url">todoist.com</div><div id="td-end-note">A calmer way to keep track.</div></div>`,
 css:`
 #stage{background:#f4eee4;color:#2b2723}#td-paper{position:absolute;inset:0;background:radial-gradient(ellipse at 80% 10%,#fffaf0,transparent 60%),linear-gradient(130deg,#f6f0e5,#eee4d7);z-index:0}#td-paper:after{content:'';position:absolute;inset:0;opacity:.28;background:repeating-linear-gradient(0deg,transparent 0,transparent 3px,#8c725408 4px)}#td-binding{position:absolute;left:66px;top:0;bottom:0;width:2px;background:#c3513326}.td-red{color:#d94332}.td-eyebrow{font-size:22px;line-height:1.2;letter-spacing:2.8px;font-weight:620}.td-thought,.td-task-title,#td-composer{font-synthesis:none}
 #td-hook{position:absolute;left:128px;top:186px;width:980px;z-index:2}#td-hook h1{font-size:150px;letter-spacing:-8px;font-weight:590;line-height:1.06;margin:65px 0 0}#td-hook h1>span{display:block;white-space:nowrap}.td-hook-rule{margin-top:66px;width:76px;height:4px;background:#d94332}.td-hook-sub{font-size:29px;margin-top:30px;color:#756e65;letter-spacing:-.4px}
 #td-thoughts{position:absolute;inset:0;z-index:3}.td-thought{position:absolute;left:0;top:0;width:690px;height:160px;padding:58px 54px 38px 93px;background:#fffcf5;border:1px solid #e4d9ca;box-shadow:0 2px 0 #e8decf,0 5px 0 #f9f4ea,0 6px 0 #ded3c4,0 30px 65px #60492e20;transform-origin:50% 50%;font-size:39px;letter-spacing:-1.2px;white-space:nowrap}.td-paper-hole{position:absolute;left:39px;top:66px;width:23px;height:23px;border:2px solid #a99b87;border-radius:50%}.td-thought-index{position:absolute;right:33px;top:15px;color:#cdbda9;font-size:16px;letter-spacing:3px}.td-thought:after{content:'';position:absolute;left:26px;right:26px;bottom:26px;height:1px;background:#e9dfd2}
 #td-app-camera{position:absolute;left:0;top:0;transform-origin:0 0;z-index:5}#td-app{position:relative;width:1600px;height:800px;border-radius:23px;background:#fff;border:1px solid #e4ded6;overflow:hidden;box-shadow:0 4px 8px #6a4c2c12,0 25px 55px #72543424,0 90px 130px #6b4c3220;color:#282828}.td-chrome{height:66px;padding:23px 25px;display:flex;align-items:center;gap:25px}.td-traffic{display:flex;gap:11px}.td-traffic i{width:13px;height:13px;background:#ff655e;border-radius:50%}.td-traffic i:nth-child(2){background:#fabc48}.td-traffic i:nth-child(3){background:#35c856}.td-sidebar-icon{width:25px;height:22px;border:1.8px solid #a5a5a5;border-radius:2px;position:relative}.td-sidebar-icon:before{content:'';position:absolute;left:7px;top:0;bottom:0;border-left:1.5px solid #a5a5a5}.td-nav-chevron{color:#aaa;font-size:32px;line-height:20px;font-weight:300}.td-app-wordmark{position:absolute;right:74px;top:19px;display:flex;align-items:center;gap:9px;color:#d94332;font-size:23px;font-weight:630;letter-spacing:-1px}.td-app-wordmark svg{width:27px;height:27px}.td-chrome-more{position:absolute;right:25px;top:22px;color:#aaa;font-size:24px;line-height:16px}
 #td-inbox-heading{position:absolute;left:118px;top:114px;font-size:48px;font-weight:650;letter-spacing:-1.6px}#td-inbox-add{position:absolute;left:118px;top:207px;display:flex;align-items:center;gap:18px;color:#8d8a86;font-size:26px}#td-inbox-add svg{width:30px;height:30px;color:#c86658}.td-section{position:absolute;left:70px;right:70px;height:65px;border-bottom:1px solid #efefef;display:flex;align-items:center;gap:17px;color:#4b4b4b;font-size:24px}.td-section>svg{width:18px;height:18px;color:#909090;margin-right:8px}.td-section b{font-weight:600}.td-section span{color:#a0a0a0;font-size:22px}.td-section i{font-style:normal;margin-left:auto;margin-right:25px;color:#999}.td-section#td-work-section{top:378px}.td-section#td-personal-section{top:504px}
 #td-app-dimmer{position:absolute;inset:66px 0 0;background:#fbfaf8e3;pointer-events:none}#td-composer{position:absolute;left:285px;top:180px;width:1120px;height:272px;border:1px solid #e5e4e0;border-radius:24px;background:white;box-shadow:0 8px 16px #25201a12,0 18px 42px #332a2024;transform-origin:50% 48%;font-family:Studio,sans-serif} .td-input{position:absolute;left:32px;top:35px;right:26px;min-height:52px;font-size:37px;line-height:1.3;letter-spacing:-1.05px;white-space:nowrap}.td-input>span{display:inline}#td-typed-date,#td-typed-priority{border-radius:3px}#td-caret{display:inline-block;vertical-align:-4px;width:2px;height:40px;background:#37312b;margin-left:2px}#td-placeholder{position:absolute;left:0;top:0;color:#aaa}.td-controls{position:absolute;left:32px;top:112px;display:flex;align-items:center;gap:10px;height:45px;white-space:nowrap}.td-chip{display:flex;align-items:center;gap:8px;padding:8px 13px;height:44px;border:1px solid #e7e7e7;border-radius:8px;font-size:24px;color:#81817e;letter-spacing:-.5px;background:#fff}.td-chip svg{width:22px;height:22px;flex:none}.td-tool-plus{width:30px;height:32px;display:block;color:#8c8c89;margin-right:3px}.td-tool-plus svg{width:26px;height:26px}.td-chip-dismiss{font-size:27px;line-height:22px;color:#93938f;margin-left:8px}#td-date-chip.active{color:#a67927;background:#fffdf8;border-color:#e8ddc6}#td-priority-chip.active{color:#b74133}#td-priority-chip.active svg{fill:#b74133;stroke:#b74133}.td-attachment{position:absolute;left:32px;bottom:28px;display:flex;align-items:center;gap:9px;border:1px solid #eee;border-radius:8px;font-size:22px;color:#94938e;padding:7px 10px}.td-attachment svg{width:24px;height:24px}#td-send-close{position:absolute;right:113px;bottom:42px;color:#b5b3ae;width:29px;height:29px}#td-send-close svg{width:100%;height:100%}#td-send{position:absolute;right:28px;bottom:24px;width:64px;height:64px;border-radius:15px;background:#d94332;color:#fff;display:grid;place-items:center;box-shadow:0 2px 0 #ad3527}#td-send svg{width:40px;height:40px}
 #td-result-row{position:absolute;left:118px;right:100px;top:210px;height:124px;border-bottom:1px solid #eae7e2;transform-origin:0 50%}.td-task-circle{display:block;width:31px;height:31px;border:2px solid #be4d41;border-radius:50%;flex:none}#td-result-row>.td-task-circle{position:absolute;left:0;top:13px}.td-task-title{position:absolute;left:53px;top:0;font-size:39px;font-weight:450;letter-spacing:-.6px}.td-task-date{position:absolute;left:53px;top:63px;display:flex;align-items:center;gap:9px;font-size:25px;color:#aa8139}.td-task-date svg{width:25px;height:25px}#td-toast{position:absolute;left:30px;bottom:26px;display:flex;align-items:center;gap:9px;padding:20px 24px;background:#292827;color:#f8f4ed;border-radius:10px;box-shadow:0 4px 12px #0002;font-size:21px}#td-toast>span{color:#e4ada2;margin:0 22px;font-size:20px}#td-toast svg{width:23px;height:23px;color:#a6a39e}
 #td-proof-label{position:absolute;left:125px;top:60px;display:flex;gap:25px;align-items:center;z-index:6}#td-proof-label span{font-size:21px;letter-spacing:3px;font-weight:650;color:#d94332}#td-proof-label b{font-weight:450;font-size:28px;letter-spacing:-.7px;color:#675d52}#td-typing-caption,#td-date-caption{position:absolute;left:128px;top:705px;z-index:6} .td-caption-kicker{display:block;font-size:19px;letter-spacing:4px;font-weight:650;color:#a09385;margin-bottom:16px}#td-typing-caption>div,#td-date-caption>div{font-size:134px;line-height:1.03;letter-spacing:-7px;font-weight:570;color:#302a25}#td-date-caption>div>span{color:#d94332}#td-submit-caption{position:absolute;left:128px;top:53px;z-index:6;display:flex;align-items:baseline;gap:40px}#td-submit-caption>div{font-size:60px;font-weight:590;letter-spacing:-2.8px}#td-submit-caption>span{font-size:19px;letter-spacing:3px;color:#a07957;font-weight:650}
 #td-cursor{position:absolute;width:43px;height:54px;z-index:12;filter:drop-shadow(0 3px 2px #30211233);transform-origin:6px 4px}#td-cursor svg{width:100%;height:100%}#td-click-ring{position:absolute;width:88px;height:88px;border:3px solid #d94332;border-radius:50%;z-index:11;transform-origin:center}#td-transfer{position:absolute;padding-left:57px;width:740px;height:110px;z-index:10;color:#282828;transform-origin:0 0}#td-transfer>.td-task-circle{position:absolute;left:0;top:8px}#td-transfer>b{display:block;font-size:39px;line-height:1.3;font-weight:450;letter-spacing:-.6px}#td-transfer>small{font-size:25px;display:flex;align-items:center;gap:9px;margin-top:13px;color:#aa8139}#td-transfer>small svg{width:25px;height:25px}
 #td-result-copy{position:absolute;left:128px;top:284px;width:580px;z-index:7}#td-result-copy>.td-eyebrow{font-size:17px;letter-spacing:2px;color:#8b7c6c;margin-bottom:38px}.td-result-line{font-size:105px;letter-spacing:-5.8px;line-height:1.06;font-weight:590;transform-origin:left center;white-space:nowrap}.td-result-copy-line{margin-top:47px;height:3px;width:76px;background:#d94332}
 #td-payoff{position:absolute;inset:0;z-index:8}.td-payoff-over{position:absolute;left:129px;top:166px;font-size:21px;letter-spacing:3px;font-weight:620;color:#847465}.td-payoff-words{position:absolute;left:128px;top:298px;font-size:171px;font-weight:570;letter-spacing:-10px;line-height:1.06}.td-payoff-words>span{display:block;white-space:nowrap}#td-paper-line{position:absolute;left:137px;right:128px;top:755px;height:2px;background:#d8c5b0;transform-origin:left center}#td-payoff-task{position:absolute;left:129px;top:824px;display:flex;align-items:center;gap:26px;padding:23px 36px;background:#fffcf5;box-shadow:0 1px 1px #8a65431f,0 12px 25px #8a654312;border:1px solid #e1d6c6;border-radius:7px;width:1270px;font-size:31px;letter-spacing:-.7px}#td-payoff-task b{font-weight:450}#td-payoff-task>span:last-child{color:#a98448;margin-left:auto;font-size:25px}
 #td-red-curtain{position:absolute;inset:0;background:#d94332;z-index:20;transform-origin:bottom center}#td-red-curtain:before{content:'';position:absolute;top:0;bottom:0;width:100%;background:linear-gradient(104deg,#ffffff03,#ffffff00 40%,#7219090c)}#td-end{position:absolute;inset:0;z-index:21;color:#fff6e9}#td-end-mark{position:absolute;left:132px;top:173px;width:113px;height:113px;color:#fff6e9;--mark-lines:#d94332}#td-end-mark svg{width:100%;height:100%}#td-end-name{position:absolute;left:122px;top:336px;font-size:249px;letter-spacing:-17px;line-height:.95;font-weight:690}#td-end-line{position:absolute;left:133px;right:135px;top:658px;height:1px;background:#ffffff52;transform-origin:left}#td-end-tag{position:absolute;left:132px;top:721px;font-size:45px;font-weight:400;letter-spacing:-1.4px}#td-end-cta{position:absolute;right:136px;top:417px;border-radius:100px;background:#fff6e9;color:#b93224;padding:24px 35px 24px 43px;display:flex;align-items:center;gap:42px;font-size:35px;letter-spacing:-1px;font-weight:550;box-shadow:0 5px 0 #ab3025}#td-end-cta svg{width:41px;height:41px}#td-end-url{position:absolute;left:132px;bottom:112px;font-size:24px;letter-spacing:-.2px;color:#fff6e9c2}#td-end-note{position:absolute;right:136px;bottom:112px;font-size:22px;color:#fff6e999;letter-spacing:-.3px}
 `,
 script:`
 const td=id=>document.getElementById(id),tdC=v=>Math.max(0,Math.min(1,v)),tdP=(f,a,b)=>tdC((f-a)/(b-a)),tdE=p=>1-Math.pow(1-p,3),tdIO=p=>p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2,tdL=(a,b,p)=>a+(b-a)*p;
 const tdA=(id,a)=>{td(id).style.opacity=String(tdC(a));td(id).style.visibility=a>0?'visible':'hidden'},tdT=(id,t)=>{td(id).style.transform=t};
 const tdPoses=[[62,840,530,.73,-6],[94,160,180,1,0],[124,-280,-125,1.46,0],[276,-280,-125,1.46,0],[314,120,168,1.05,0],[366,120,168,1.05,0],[408,665,204,.745,0],[532,665,204,.745,0],[570,1060,120,.67,4]];
 function tdCamera(n){let v=tdPoses[0];for(let i=1;i<tdPoses.length;i++){const b=tdPoses[i];if(n<=b[0]){const p=tdIO(tdP(n,v[0],b[0]));return v.slice(1).map((x,j)=>tdL(x,b[j+1],p));}v=b;}return v.slice(1)}
 function draw(frame){
  const n=Math.max(0,Math.min(719,Math.round(frame))),hookOut=tdE(tdP(n,61,83));
  tdA('td-paper',1);tdA('td-binding',1-tdP(n,66,94));
  tdA('td-hook',1-hookOut);tdT('td-hook','translateY('+(-180*hookOut)+'px)');
  tdA('td-too',1);tdT('td-too','translateY('+(16*(1-tdE(tdP(n,0,15))))+'px)');
  tdA('td-mind',1);tdT('td-mind','translateY('+(20*(1-tdE(tdP(n,0,20))))+'px)');
  tdA('td-thoughts',1-tdP(n,68,87));
  const thoughtPos=[[1225,128,-8],[1090,454,5],[1245,774,-5]];
  thoughtPos.forEach((v,i)=>{const enter=tdE(tdP(n,5+i*8,25+i*8)),align=tdIO(tdP(n,53+i*3,83));tdT('td-thought-'+i,'translate('+tdL(v[0]+130*(1-enter),580,align)+'px,'+tdL(v[1]+75*(1-enter),365+i*8,align)+'px) rotate('+tdL(v[2],0,align)+'deg) scale('+tdL(1,.7,align)+')');tdA('td-thought-'+i,enter);});
  const appOpacity=tdP(n,62,79)*(1-tdP(n,551,574)),cam=tdCamera(n);tdA('td-app-camera',appOpacity);tdT('td-app-camera','translate('+cam[0]+'px,'+cam[1]+'px) scale('+cam[2]+') rotate('+cam[3]+'deg)');
  const compIn=tdE(tdP(n,81,101)),compOut=tdE(tdP(n,340,354));tdA('td-composer',compIn*(1-compOut));tdT('td-composer','translateY('+(23*(1-compIn)-18*compOut)+'px) scale('+tdL(.95,1,compIn)+')');tdA('td-app-dimmer',.8*compIn*(1-compOut));
  const task='Meet with Ada',date=' tomorrow at 14',priority=' p1';
  const t1=task.slice(0,Math.floor(task.length*tdP(n,111,157))),t2=date.slice(0,Math.floor(date.length*tdP(n,160,218))),t3=priority.slice(0,Math.floor(priority.length*tdP(n,230,249)));
  td('td-typed-task').textContent=t1;td('td-typed-date').textContent=t2;td('td-typed-priority').textContent=t3;
  tdA('td-placeholder',n<112?1:0);tdA('td-caret',n<333?((Math.floor(n/15)%2)===0?1:.15):0);
  const dateReady=n>=195,fullDate=n>=218,priorityReady=n>=249;
  td('td-typed-date').style.background=dateReady?'#faeadf':'transparent';td('td-typed-priority').style.background=priorityReady?'#faeadf':'transparent';
  td('td-date-value').textContent=fullDate?'Tomorrow 14:00':dateReady?'Tomorrow':'Date';td('td-date-chip').className='td-chip'+(dateReady?' active':'');tdA('td-date-dismiss',dateReady?1:0);td('td-date-dismiss').style.display=dateReady?'inline':'none';
  td('td-priority-value').textContent=priorityReady?'P1':'Priority';td('td-priority-chip').className='td-chip'+(priorityReady?' active':'');tdA('td-priority-dismiss',priorityReady?1:0);td('td-priority-dismiss').style.display=priorityReady?'inline':'none';
  const chipPop=1+.065*Math.sin(Math.PI*tdP(n,195,211));tdT('td-date-chip','scale('+chipPop+')');tdT('td-priority-chip','scale('+(1+.075*Math.sin(Math.PI*tdP(n,249,264)))+')');
  tdA('td-proof-label',tdP(n,69,84)*(1-tdP(n,107,121)));tdT('td-proof-label','translateY('+(20*(1-tdE(tdP(n,69,88))))+'px)');
  tdA('td-typing-caption',tdP(n,116,134)*(1-tdP(n,185,197)));tdT('td-typing-caption','translateY('+(36*(1-tdE(tdP(n,116,136)))-32*tdP(n,185,197))+'px)');
  tdA('td-date-caption',tdP(n,199,216)*(1-tdP(n,277,291)));tdT('td-date-caption','translateY('+(42*(1-tdE(tdP(n,199,218)))-35*tdP(n,277,291))+'px)');
  tdA('td-submit-caption',tdP(n,304,318)*(1-tdP(n,373,389)));tdT('td-submit-caption','translateY('+(18*(1-tdE(tdP(n,304,319))))+'px)');
  const clickX=cam[0]+1345*cam[2],clickY=cam[1]+396*cam[2],move=tdIO(tdP(n,307,330)),cursorX=tdL(1780,clickX,move),cursorY=tdL(865,clickY,move);
  tdA('td-cursor',tdP(n,306,312)*(1-tdP(n,348,359)));tdT('td-cursor','translate('+cursorX+'px,'+cursorY+'px) scale('+(1-.18*Math.sin(Math.PI*tdP(n,334,343)))+')');
  const pulse=tdP(n,337,354);tdA('td-click-ring',(n>=337?1:0)*(1-pulse));tdT('td-click-ring','translate('+(clickX-44)+'px,'+(clickY-44)+'px) scale('+tdL(.5,1.55,pulse)+')');
  tdT('td-send','scale('+(1-.09*Math.sin(Math.PI*tdP(n,335,344)))+')');
  const result=tdE(tdP(n,342,364));tdA('td-result-row',n>=364?1:0);tdT('td-result-row','translateY(0)');
  tdT('td-inbox-add','translateY('+(result*144)+'px)');tdT('td-work-section','translateY('+(result*66)+'px)');tdT('td-personal-section','translateY('+(result*66)+'px)');
  const transfer=tdIO(tdP(n,342,364)),tx=tdL(317,118,transfer),ty=tdL(220,210,transfer);tdA('td-transfer',n>=342&&n<364?1:0);tdT('td-transfer','translate('+(cam[0]+tx*cam[2])+'px,'+(cam[1]+ty*cam[2])+'px) scale('+cam[2]+')');
  tdA('td-toast',tdP(n,363,375)*(1-tdP(n,462,480)));tdT('td-toast','translateY('+(18*(1-tdE(tdP(n,363,378))))+'px)');
  tdA('td-result-copy',tdP(n,388,407)*(1-tdP(n,530,550)));[0,1,2].forEach(i=>tdT('td-result-line-'+i,'translateY('+(45*(1-tdE(tdP(n,390+i*5,414+i*5))))+'px)'));
  tdA('td-payoff',tdP(n,546,563)*(1-tdP(n,608,629)));tdT('td-payoff','translateY('+(45*(1-tdE(tdP(n,546,569))))+'px)');tdT('td-space-a','translateX('+(-75*(1-tdE(tdP(n,548,570))))+'px)');tdT('td-space-b','translateX('+(110*(1-tdE(tdP(n,554,579))))+'px)');tdT('td-paper-line','scaleX('+tdE(tdP(n,562,583))+')');tdA('td-payoff-task',tdP(n,566,578));tdT('td-payoff-task','translateX('+(150*(1-tdE(tdP(n,562,589))))+'px)');
  const curtain=tdIO(tdP(n,611,637));tdA('td-red-curtain',n>=611?1:0);tdT('td-red-curtain','translateY('+(1080*(1-curtain))+'px)');
  tdA('td-end',tdP(n,632,644));tdT('td-end-mark','translateY('+(32*(1-tdE(tdP(n,636,654))))+'px)');tdT('td-end-name','translateY('+(80*(1-tdE(tdP(n,637,659))))+'px)');tdT('td-end-line','scaleX('+tdE(tdP(n,646,673))+')');tdT('td-end-tag','translateY('+(27*(1-tdE(tdP(n,648,670))))+'px)');tdT('td-end-cta','translateX('+(90*(1-tdE(tdP(n,650,675))))+'px)');tdA('td-end-url',tdP(n,660,679));tdA('td-end-note',tdP(n,664,683));
 }
 `,
 reviewFrames:[0,20,48,72,92,124,158,195,221,264,310,337,350,364,408,460,529,558,593,626,659,688,719],
 notes:[
  'Manually art-directed illustrative product launch film; not successful automatic URL generation. Prior failed URL acceptance remains unchanged.',
  'Single desktop Todoist Quick Add/Inbox identity, grounded in the official help-page demonstration retained in .local/launch-todoist-sourcepack-20261003. All pixels here are authored HTML/SVG, never screenshot pans.',
  'Observed mechanism: task entry, natural-language Tomorrow14:00 and P1 recognition, red-arrow confirmation, persistent Meet with Ada row in Inbox. The row is added, not marked completed. Reminder controls from the source are omitted rather than promoted.',
  'Editorial thought cards and one-person-business framing are illustrative. UI chrome is selectively simplified for readable film staging; no mobile or Today interface is mixed into the workflow.',
  'Warm cream/red, physical paper motif, typography and task continuity are manually authored art direction. This does not establish reference parity or automated-engine creative quality.',
  'The public source demonstration is silent. Soundtrack is supplied separately by the root render workflow; no listening assessment is claimed by this source file.'
 ]
};
