import type { MotionStudy } from './types';

/** Review UI only; requestAnimationFrame here never drives exported picture. */
export function comparisonViewer(study: MotionStudy) {
  const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(study.title)}</title><style>
@font-face{font-family:Studio;src:url('project/assets/Geist.woff2');font-weight:100 900}*{box-sizing:border-box}body{margin:0;background:#f5f5f7;color:#161617;font-family:Studio,Arial,sans-serif}main{max-width:1600px;margin:56px auto;padding:0 32px}h1{font-size:36px;letter-spacing:-.05em;font-weight:600;margin:0 0 10px}p{color:#6e6e73;line-height:1.6;margin:0 0 28px}.views{display:grid;grid-template-columns:1fr 1fr;gap:18px}.view{background:#fff;border:1px solid #e5e5e8;border-radius:18px;overflow:hidden}h2{font-size:13px;font-weight:600;letter-spacing:.035em;margin:18px 20px;text-transform:uppercase}video{width:100%;display:block;aspect-ratio:16/9;background:#000}nav{display:flex;align-items:center;gap:12px;margin:24px 0}button,a{font:inherit;font-size:14px;border:0;border-radius:999px;padding:12px 18px;background:#e8e8ed;color:#161617;text-decoration:none;cursor:pointer}button.primary{background:#171719;color:white}input[type=range]{flex:1;accent-color:#171719}output{font-size:13px;font-variant-numeric:tabular-nums;width:180px;text-align:right}details{background:white;padding:20px 24px;border:1px solid #e5e5e8;border-radius:16px;margin-top:28px;color:#6e6e73;font-size:14px;line-height:1.7}summary{color:#161617;cursor:pointer}ul{padding-left:20px}footer{display:flex;gap:12px;margin-top:24px}@media(max-width:850px){main{margin:28px auto;padding:0 16px}.views{grid-template-columns:1fr}nav{flex-wrap:wrap}input[type=range]{min-width:200px}h1{font-size:29px}}
</style></head><body><main><h1>${escape(study.title)}</h1><p>Reference on the left. Editable HTML reconstruction on the right. Silent, manually authored design study.</p><div class="views"><section class="view"><h2>Original reference</h2><video id="ref" src="reference-selection.mp4" muted playsinline preload="auto"></video></section><section class="view"><h2>Our HTML engine</h2><video id="ours" src="replication.mp4" muted playsinline preload="auto"></video></section></div><nav><button id="play" class="primary">Play comparison</button><button id="prev" aria-label="Previous frame">←</button><button id="next" aria-label="Next frame">→</button><input id="seek" aria-label="Comparison frame" type="range" min="0" max="${study.durationFrames - 1}" step="1" value="0"><output id="time"></output></nav><p>Use the arrow buttons to step one frame at a time. Original range: ${study.reference.startSeconds.toFixed(3)}–${(study.reference.startSeconds + study.durationFrames / 30).toFixed(3)} seconds.</p><details><summary>What was reproduced, and remaining differences</summary><ul>${study.notes.map(note => `<li>${escape(note)}</li>`).join('')}</ul><p>Export checks compare the MP4 with our HTML, not with the reference. They do not score artistic similarity.</p></details><footer><a href="project/index.html">Editable HTML composition</a><a href="replication.mp4" download>Download reconstruction</a><a href="comparison.mp4" download>Download comparison</a></footer></main><script>
const ref=document.getElementById('ref'),ours=document.getElementById('ours'),slider=document.getElementById('seek'),label=document.getElementById('time'),play=document.getElementById('play');let playing=false,frame=0;
function update(){label.textContent='Frame '+frame+' / ${study.durationFrames - 1} · '+(frame/30).toFixed(3)+'s';slider.value=frame;}
function seek(n){playing=false;ref.pause();ours.pause();play.textContent='Play comparison';frame=Math.max(0,Math.min(${study.durationFrames - 1},n));ref.currentTime=(frame+.01)/30;ours.currentTime=(frame+.01)/30;update();}
play.onclick=async()=>{if(playing){seek(Math.floor(ref.currentTime*30));return;}if(frame>=${study.durationFrames - 1})seek(0);playing=true;play.textContent='Pause';await Promise.all([ref.play(),ours.play()]);};slider.oninput=()=>seek(Number(slider.value));document.getElementById('prev').onclick=()=>seek(frame-1);document.getElementById('next').onclick=()=>seek(frame+1);ref.onended=()=>seek(${study.durationFrames - 1});
function tick(){if(playing){frame=Math.min(${study.durationFrames - 1},Math.floor(ref.currentTime*30));if(Math.abs(ref.currentTime-ours.currentTime)>.045)ours.currentTime=ref.currentTime;update();}requestAnimationFrame(tick);}update();tick();
</script></body></html>`;
}
