import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { neon } from "@neondatabase/serverless";
import { del } from "@vercel/blob";
import { generateClientTokenFromReadWriteToken, put } from "@vercel/blob/client";
import { splitSql } from "../db/split-sql";
import { query } from "../lib/server/db";
import { ownedUpload, prepareUpload, verifyUpload } from "../lib/server/uploads";
import { claimNextJob, checkpointJob, createJob, getJobForWorker } from "../lib/server/jobs";
import { workerToken } from "../lib/server/worker-auth";
import { POST as artifactPost, GET as artifactGet } from "../app/api/internal/jobs/[id]/artifact/route";
import { POST as checkpointPost } from "../app/api/internal/jobs/[id]/checkpoint/route";

test("private scoped Blob uploads are owner-bound and verified against real stored bytes", { skip: process.env.STUDIO_STORAGE_INTEGRATION !== "1" }, async () => {
  assert.ok(process.env.DATABASE_URL && process.env.BLOB_READ_WRITE_TOKEN);
  const admin = neon(process.env.DATABASE_URL);
  const schemaName = `studio_test_${randomUUID().replaceAll("-", "")}`;
  const originalNodeEnv = process.env.NODE_ENV;
  const originalWorkerSecret = process.env.WORKER_SECRET;
  const uploaded: string[] = [];
  try {
    const schema = await readFile(new URL("../db/schema.sql", import.meta.url), "utf8");
    await admin.transaction([admin.query(`CREATE SCHEMA ${schemaName}`), admin.query(`SET LOCAL search_path TO ${schemaName},public`), ...splitSql(schema).map(statement => admin.query(statement))]);
    Object.assign(process.env, { NODE_ENV: "test", STUDIO_DB_TEST_SCHEMA: schemaName });
    process.env.WORKER_SECRET = "storage-integration-only-worker-secret-32-characters";
    assert.equal((await query<{ current_schema: string }>("SELECT current_schema()"))[0].current_schema, schemaName);
    const users = await query<{ id: string }>("INSERT INTO studio_users(email,name) VALUES('owner@example.org','Owner'),('other@example.org','Other') RETURNING id");
    const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6qukAAAAASUVORK5CYII=", "base64");
    const item = await prepareUpload(users[0].id, { name: "test-screen.png", size: png.length, contentType: "image/png", kind: "asset" });
    await assert.rejects(ownedUpload(item.id, users[1].id), /could not be found/);
    const token = await generateClientTokenFromReadWriteToken({ pathname: item.pathname, maximumSizeInBytes: png.length, allowedContentTypes: ["image/png"], addRandomSuffix: false, allowOverwrite: false, validUntil: Date.now() + 120_000 });
    const blob = await put(item.pathname, png, { access: "private", contentType: "image/png", token });
    uploaded.push(blob.url);
    assert.match(blob.url, /^https:\/\/[^/]+\.private\.blob\.vercel-storage\.com\//);
    const anonymous = await fetch(blob.url, { cache: "no-store", signal: AbortSignal.timeout(10_000) });
    await anonymous.body?.cancel();
    assert.equal(anonymous.ok, false, "The private source must not be readable without authorization");
    const verified = await verifyUpload(await ownedUpload(item.id, users[0].id));
    assert.equal(verified.id, item.id); assert.equal(verified.size, png.length);
    assert.equal((await ownedUpload(item.id, users[0].id)).status, "ready");
    await assert.rejects(put(item.pathname, png, { access: "private", contentType: "image/png", token }), /exist|overwrite/i, "The scoped token must not overwrite a verified source");

    const job = await createJob(users[0].id, { mode: "url", productUrl: "https://vercel.com", videoType: "launch", format: "auto", uploadIds: [item.id], idempotencyKey: randomUUID() });
    const active = await claimNextJob({ workerId: "storage-integration" }); assert.equal(active?.id, job.id); assert.ok(active?.lease_token);
    const worker = workerToken(job.id, active.lease_token);
    const context = { params: Promise.resolve({ id: job.id }) };
    const request = (body: unknown, bearer = worker) => new Request(`https://studio.example.org/api/internal/jobs/${job.id}/artifact`, { method: "POST", headers: { authorization: `Bearer ${bearer}`, "content-type": "application/json" }, body: JSON.stringify(body) });
    const source = await artifactGet(new Request(`https://studio.example.org/api/internal/jobs/${job.id}/artifact?upload=${item.id}`, { headers: { authorization: `Bearer ${worker}` } }), context);
    assert.equal(source.status, 200); assert.deepEqual(Buffer.from(await source.arrayBuffer()), png);
    const unavailable = await artifactGet(new Request(`https://studio.example.org/api/internal/jobs/${job.id}/artifact?upload=${randomUUID()}`, { headers: { authorization: `Bearer ${worker}` } }), context);
    assert.equal(unavailable.status, 404);
    const wrongScope = await artifactPost(request({ operation: "prepare", path: "ledger.json", size: 8, contentType: "application/json" }, workerToken(randomUUID(), active.lease_token)), context);
    assert.equal(wrongScope.status, 403);
    const traversal = await artifactPost(request({ operation: "prepare", path: "../outside.json", size: 8, contentType: "application/json" }), context);
    assert.equal(traversal.status, 400);
    const bytes = Buffer.from('{"checkpoint":"durable"}');
    const prepared = await artifactPost(request({ operation: "prepare", path: "analysis/test.json", size: bytes.length, contentType: "application/json" }), context);
    assert.equal(prepared.status, 200); const grant = await prepared.json();
    const artifact = await put(grant.pathname, bytes, { access: "private", contentType: "application/json", token: grant.clientToken }); uploaded.push(artifact.url);
    const wrongPath = await artifactPost(request({ operation: "complete", path: "other.json", url: artifact.url, grant: grant.grant }), context);
    assert.equal(wrongPath.status, 403);
    const completion = await artifactPost(request({ operation: "complete", path: "analysis/test.json", url: artifact.url, grant: grant.grant }), context);
    assert.equal(completion.status, 200);
    const fetched = await artifactGet(new Request(`https://studio.example.org/api/internal/jobs/${job.id}/artifact?path=analysis%2Ftest.json`, { headers: { authorization: `Bearer ${worker}` } }), context);
    assert.equal(fetched.status, 200); assert.deepEqual(Buffer.from(await fetched.arrayBuffer()), bytes);
    await checkpointJob(job.id, active.lease_token, "reading", { sandboxName: `video-studio-job-${job.id}-1` });
    const reserved = await checkpointPost(request({ status: "planning", checkpoint: { sandboxName: "video-studio-job-another-owner-1" } }), context);
    assert.equal(reserved.status, 400);
    assert.equal((await getJobForWorker(job.id))?.checkpoint.sandboxName, `video-studio-job-${job.id}-1`);
    const valid = await checkpointPost(request({ status: "planning", checkpoint: { stage: "plan" } }), context);
    assert.equal(valid.status, 200);

    const invalid = Buffer.from("<html>not an image</html>");
    const fake = await prepareUpload(users[0].id, { name: "fake.png", size: invalid.length, contentType: "image/png", kind: "asset" });
    const fakeToken = await generateClientTokenFromReadWriteToken({ pathname: fake.pathname, maximumSizeInBytes: invalid.length, allowedContentTypes: ["image/png"], addRandomSuffix: false, allowOverwrite: false, validUntil: Date.now() + 120_000 });
    const fakeBlob = await put(fake.pathname, invalid, { access: "private", contentType: "image/png", token: fakeToken });
    uploaded.push(fakeBlob.url);
    await assert.rejects(verifyUpload(await ownedUpload(fake.id, users[0].id)), /doesn't contain/);
    await assert.rejects(ownedUpload(fake.id, users[0].id), /could not be found/);
  } finally {
    if (uploaded.length) await del(uploaded);
    delete process.env.STUDIO_DB_TEST_SCHEMA;
    if (originalWorkerSecret === undefined) delete process.env.WORKER_SECRET; else process.env.WORKER_SECRET = originalWorkerSecret;
    if (originalNodeEnv === undefined) delete (process.env as Record<string, string | undefined>).NODE_ENV; else Object.assign(process.env, { NODE_ENV: originalNodeEnv });
    await admin.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
  }
});
