import Link from "next/link";
import { ArrowDown, ArrowUpRight, AudioLines, Clapperboard, Layers3, LockKeyhole } from "lucide-react";
import { AccessPanel } from "@/components/access-panel";
import { Brand, FilmArtwork } from "@/components/brand";

export default function Home() {
  return <div className="landing"><header className="landing-nav"><Brand/><nav aria-label="Main navigation"><a className="nav-text" href="#how-it-works">How it works</a><a className="button button-secondary button-small" href="#your-invitation">Enter studio <ArrowUpRight size={15}/></a></nav></header>
    <main id="main-content"><section className="landing-hero"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> Your next launch starts here</span><h1>Your product.<br/><span>In motion.</span></h1><p className="hero-description">You built something worth showing.<br className="desktop-break"/> Turn it into a video worth watching.</p><p className="hero-detail">Share your product link or PRD. Get a finished launch or feature-demo video, made with your real product visuals.</p><div id="your-invitation" className="hero-access"><AccessPanel/></div></div><div className="hero-art"><FilmArtwork/><div className="hero-art-footer"><span><Clapperboard size={15}/> From product to premiere</span><span>Made for software.</span></div></div></section>
      <section className="landing-how" id="how-it-works"><div className="section-heading"><div><span className="eyebrow">Less production. More possibility.</span><h2>One submission.<br/>A complete video.</h2></div><ArrowDown size={26} strokeWidth={1.4} aria-hidden="true"/></div><div className="how-grid"><article><span className="how-number">01</span><Layers3 size={23} strokeWidth={1.4}/><h3>Start with your product</h3><p>A public product link is enough to begin. Or bring a PRD with screenshots and recordings.</p></article><article><span className="how-number">02</span><Clapperboard size={23} strokeWidth={1.4}/><h3>Leave the craft to us</h3><p>Product facts, visual storytelling, typography, and motion come together automatically.</p></article><article><span className="how-number">03</span><AudioLines size={23} strokeWidth={1.4}/><h3>Make your entrance</h3><p>Preview and download your finished MP4, with instrumental music and sound effects.</p></article></div></section>
      <section className="landing-note"><LockKeyhole size={19}/><p>Your products and videos stay in your private studio.<br/><span>A thoughtful space to prepare your next release.</span></p><Link className="text-link" href="/invite">Have an invitation? <ArrowUpRight size={16}/></Link></section>
    </main><footer className="landing-footer"><Brand compact/><span>Built for the things you’re building.</span><span>Free private beta</span></footer>
  </div>;
}
