"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Check, CircleCheck, Clock3, Download, ExternalLink, FileText, Film, ImageIcon, LoaderCircle, LockKeyhole, RotateCw } from "lucide-react";
import { STAGES, STAGE_LABELS, type JobDetail as Job } from "@/lib/contracts";
import { formatBytes, formatDate } from "./studio-context";
import { ACTIVE_STATUSES } from "./job-library";
import { usePollingResource } from "./use-polling-resource";

const stageDescriptions = { queued: "Your video is in the queue, ready for its turn.", reading: "Getting to know your product and finding the visuals that tell its story.", planning: "Finding the right structure, words, and rhythm for your video.", rendering: "Bringing your product visuals, motion, and sound together.", checking: "Checking the finished video for clarity, accuracy, and technical quality.", ready: "Your video has passed its checks and is ready to share." };
function elapsedLabel(start: string, end: number) { const seconds = Math.max(0, Math.floor((end - new Date(start).getTime()) / 1000)); if (seconds < 60) return `${seconds}s`; const minutes = Math.floor(seconds / 60); return minutes < 60 ? `${minutes}m ${seconds % 60}s` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`; }

export function JobDetail({ id }: { id: string }) {
  const [pollingInterval, setPollingInterval] = useState<number | null>(5000);
  const { data, loading, error, refresh: fetchJob } = usePollingResource<{ job: Job }>(`/api/jobs/${encodeURIComponent(id)}`, pollingInterval);
  const job = data?.job || null;
  const [now, setNow] = useState(Date.now());
  const [mediaError, setMediaError] = useState(false);
  useEffect(() => { setPollingInterval(job && !ACTIVE_STATUSES.includes(job.status) ? null : 5000); }, [job?.status]);
  useEffect(() => { if (!job || !ACTIVE_STATUSES.includes(job.status)) return; const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [job?.status]);
  if (loading) return <div className="loading-state" role="status"><LoaderCircle className="spin" size={24}/><p>Opening your video…</p></div>;
  if (!job) return <div className="filter-empty"><AlertCircle size={28}/><h1>We couldn’t open this video.</h1><p role="alert">{error || "It may no longer be available in your workspace."}</p><button className="button button-primary" onClick={() => void fetchJob()}><RotateCw size={16}/> Try again</button><Link className="text-link" href="/studio">Back to your videos</Link></div>;
  const active = ACTIVE_STATUSES.includes(job.status);
  const ready = job.status === "ready" && job.qualityPassed;
  const stopped = !active && !ready;
  const stageIndex = STAGES.indexOf(job.status as typeof STAGES[number]);
  const end = active ? now : new Date(job.completedAt || job.updatedAt).getTime();
  const info = job.status in stageDescriptions ? stageDescriptions[job.status as keyof typeof stageDescriptions] : "Your video needs attention before we can deliver it.";
  return <><Link className="back-link" href="/studio"><ArrowLeft size={15}/> Your videos</Link><div className="page-heading detail-heading"><div><div className="eyebrow">{job.videoType === "launch" ? "Product launch" : "Feature demo"}</div><h1>{job.title}</h1><p>Created {formatDate(job.createdAt)} <span className="inline-dot">·</span> {job.width && job.height ? `${job.width} × ${job.height}` : job.format === "auto" ? "Auto format" : job.format}</p></div>{ready && <a className="button button-primary" href={`/api/jobs/${job.id}/media?kind=video&download=1`}><Download size={17}/> Download MP4</a>}</div>
    {error && <div className="notice notice-neutral" role="status"><AlertCircle size={18}/><div><strong>Updates are temporarily unavailable.</strong><p>{error} Your job can continue in the background.</p></div><button className="button button-secondary button-small" onClick={() => void fetchJob()}>Refresh</button></div>}
    <div className="job-detail-layout"><div className="job-primary">{ready ? <div className="delivery-card"><div className="video-player-wrap"><video controls preload="metadata" playsInline poster={`/api/jobs/${job.id}/media?kind=poster`} src={`/api/jobs/${job.id}/media?kind=video`} aria-label={`Preview of ${job.title}`} onError={() => setMediaError(true)}/></div>{mediaError && <p className="form-error media-error" role="alert">The preview couldn’t load. Try refreshing, or use Download MP4.</p>}<div className="delivery-caption"><div><CircleCheck size={20}/><div><strong>Your moment is ready.</strong><p>Checked, finished, and ready to make an entrance.</p></div></div><span>{job.durationSeconds ? `${Math.round(job.durationSeconds)} sec · ` : ""}MP4</span></div></div> : stopped ? <div className="job-stopped"><span className="stopped-icon"><AlertCircle size={30} strokeWidth={1.4}/></span><span className="eyebrow">A little attention needed</span><h2>{job.status === "needs_input" ? "Let’s give your story a little more." : job.status === "needs_review" || job.status === "ready" ? "This video needs another look." : job.status === "cancelled" ? "This video was cancelled." : "We couldn’t finish this one."}</h2><p>{job.error?.message || (job.status === "ready" ? "Your video’s quality checks haven’t been confirmed, so it isn’t available to preview or download yet." : "This submission didn’t produce a finished video.")}</p>{job.error?.action && <div className="recovery-note"><strong>For your next submission</strong><p>{job.error.action}</p></div>}<Link className="button button-primary" href="/studio/new">Start a new video <ArrowRight size={17}/></Link></div> : <div className="processing-card"><div className="processing-visual" aria-hidden="true"><div className="processing-ring ring-one"/><div className="processing-ring ring-two"/><span><Film size={33} strokeWidth={1.3}/></span><i/><i/><i/></div><span className="eyebrow">Something good is taking shape</span><h2 aria-live="polite" aria-atomic="true">{STAGE_LABELS[job.status]}</h2><p>{info}</p><span className="elapsed-pill"><Clock3 size={14}/>{elapsedLabel(job.createdAt, end)} elapsed</span><div className="background-note"><LockKeyhole size={14}/><span>You can leave this page. Your video will keep moving.</span></div></div>}
      <section className="job-source-card"><div className="section-title-row"><h2>The starting point</h2><span>{job.mode === "url" ? "Product URL" : "Product brief"}</span></div>{job.productUrl && <a className="source-link" href={job.productUrl} target="_blank" rel="noreferrer noopener"><span>{job.productUrl}</span><ExternalLink size={15}/></a>}{job.uploads.length > 0 && <ul className="source-files">{job.uploads.map((file) => <li key={file.id}>{file.kind === "prd" ? <FileText size={18}/> : file.kind === "reference" ? <Film size={18}/> : <ImageIcon size={18}/>}<div><strong>{file.name}</strong><span>{file.kind === "prd" ? "Product brief" : file.kind === "reference" ? "Style reference" : "Product visual"} · {formatBytes(file.size)}</span></div></li>)}</ul>}{!job.productUrl && job.uploads.length === 0 && <p className="field-hint">Source details are unavailable.</p>}</section>
    </div><aside className="job-progress"><div className="progress-heading"><h2>The process</h2>{ready ? <CircleCheck size={18}/> : <span>{elapsedLabel(job.createdAt, end)}</span>}</div><ol className="stage-list">{STAGES.map((stage, index) => { const done = ready || (stageIndex > index) || (stopped && job.stages.some((entry) => entry.stage === STAGES[index + 1])); const current = active && stageIndex === index; return <li key={stage} className={`${done ? "done" : ""}${current ? " current" : ""}`} aria-current={current ? "step" : undefined}><span className="stage-indicator">{done ? <Check size={13} strokeWidth={2.5}/> : current ? <span/> : index + 1}</span><span><strong>{STAGE_LABELS[stage]}</strong>{current && <small>In progress</small>}{done && stage === "ready" && <small>Ready to download</small>}</span></li>; })}</ol><div className="progress-footer"><ShieldIcon/><p>{ready ? "The final video is available only to you." : "Each video is checked before it reaches you."}</p></div><div className="job-reference"><span>Submission ID</span><code>{job.id}</code></div></aside></div>
  </>;
}
function ShieldIcon() { return <LockKeyhole size={15}/>; }
