"use client";

import { useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, ArrowUpRight, AudioLines, Check, ChevronDown, Clapperboard, FileText, Globe2, Layers3, Link2, LoaderCircle, LockKeyhole, Monitor, MousePointer2, RectangleVertical, ShieldCheck, Sparkles, Square } from "lucide-react";
import type { CreateJobInput, InputMode, JobDetail, OutputFormat, VideoType } from "@/lib/contracts";
import { api, formatBytes, useStudio } from "./studio-context";
import { FilmArtwork } from "./brand";
import { UploadField, type SelectedUpload } from "./upload-field";

const formats: { value: OutputFormat; label: string; detail: string; icon: typeof Monitor }[] = [{ value: "auto", label: "Auto", detail: "Recommended", icon: Sparkles }, { value: "16:9", label: "Landscape", detail: "16:9", icon: Monitor }, { value: "9:16", label: "Vertical", detail: "9:16", icon: RectangleVertical }, { value: "1:1", label: "Square", detail: "1:1", icon: Square }];

export function NewVideoForm() {
  const { session } = useStudio();
  const router = useRouter();
  const [mode, setMode] = useState<InputMode>("url");
  const [productUrl, setProductUrl] = useState("");
  const [videoType, setVideoType] = useState<VideoType>("launch");
  const [format, setFormat] = useState<OutputFormat>("auto");
  const [prd, setPrd] = useState<SelectedUpload[]>([]);
  const [assets, setAssets] = useState<SelectedUpload[]>([]);
  const [reference, setReference] = useState<SelectedUpload[]>([]);
  const [referenceMode, setReferenceMode] = useState<"upload" | "link">("upload");
  const [referenceUrl, setReferenceUrl] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const request = useRef<{ fingerprint: string; key: string } | null>(null);
  const errorBox = useRef<HTMLDivElement>(null);
  if (!session) return null;
  const files = [...(mode === "prd" ? prd : []), ...assets, ...(referenceMode === "upload" ? reference : [])];
  const uploading = files.some((file) => !file.record && !file.error);
  const failedUpload = files.some((file) => file.error);
  const missingSource = mode === "url" ? !productUrl.trim() : prd.length === 0 || assets.length === 0;
  const canSubmit = !busy && !uploading && !failedUpload && !missingSource && session.acceptingJobs;
  const prdFiles = mode === "prd" ? prd : [];
  const referenceFiles = referenceMode === "upload" ? reference : [];
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!canSubmit) return;
    setBusy(true); setError(null);
    const values = { mode, productUrl: mode === "url" ? productUrl.trim() : undefined, videoType, format, uploadIds: files.flatMap((file) => file.record ? [file.record.id] : []), referenceUrl: referenceMode === "link" && referenceUrl.trim() ? referenceUrl.trim() : undefined };
    const fingerprint = JSON.stringify(values);
    if (!request.current || request.current.fingerprint !== fingerprint) request.current = { fingerprint, key: crypto.randomUUID() };
    const input: CreateJobInput = { ...values, idempotencyKey: request.current.key };
    try { const { job } = await api<{ job: JobDetail }>("/api/jobs", { method: "POST", body: JSON.stringify(input) }); router.push(`/studio/jobs/${job.id}`); }
    catch (error) { setError(error instanceof Error ? error.message : "We couldn’t start your video. Please try again."); setBusy(false); requestAnimationFrame(() => errorBox.current?.focus()); }
  }
  return <><div className="page-heading"><div><div className="eyebrow">From idea to introduction</div><h1>Give your product a moment.</h1><p>Bring the product. We’ll bring it to life.</p></div><span className="heading-icon" aria-hidden="true"><Clapperboard size={26} strokeWidth={1.4}/></span></div>
    <div className="create-layout"><form className="creation-form" onSubmit={submit} onInvalid={(event) => { (event.target as HTMLElement).closest("details")?.setAttribute("open", ""); }}>
      {!session.acceptingJobs && <div className="notice notice-neutral" role="status"><ShieldCheck size={19}/><div><strong>The studio is getting ready.</strong><p>Video generation is paused while the private beta is being configured. You can explore the form and come back when it’s ready.</p></div></div>}
      <section className="form-section"><div className="form-section-heading"><span className="step-number">01</span><div><h2>Start with your product</h2><p>One starting point. Everything we need to get to know it.</p></div></div>
        <fieldset className="segmented-control source-control" disabled={busy}><legend className="visually-hidden">Product source</legend><label className={mode === "url" ? "selected" : ""}><input type="radio" name="mode" value="url" checked={mode === "url"} onChange={() => setMode("url")}/><Globe2 size={16}/> Product URL</label><label className={mode === "prd" ? "selected" : ""}><input type="radio" name="mode" value="prd" checked={mode === "prd"} onChange={() => setMode("prd")}/><FileText size={16}/> Product brief</label></fieldset>
        {mode === "url" ? <div className="source-input"><label htmlFor="product-url">Product URL</label><div className="input-with-icon"><Link2 size={17}/><input id="product-url" type="url" inputMode="url" placeholder="https://your-product.com" value={productUrl} required disabled={busy} onChange={(event) => setProductUrl(event.target.value)} onBlur={() => { if (productUrl.trim() && !/^[a-z][a-z\d+.-]*:/i.test(productUrl.trim())) setProductUrl(`https://${productUrl.trim()}`); }} aria-describedby="product-url-hint"/></div><p id="product-url-hint" className="field-hint">A public page with useful product details and visuals. No login required.</p></div> : <div className="source-input"><span className="field-label">Product brief <span className="required-note">Required</span></span><UploadField kind="prd" files={prd} onChange={setPrd} limits={session.limits} otherFiles={[...assets, ...referenceFiles]} disabled={busy}/></div>}
        <div className="assets-input"><div className="field-label-row"><span className="field-label">Product visuals <span className={mode === "prd" ? "required-note" : "optional-note"}>{mode === "prd" ? "Required" : "Optional"}</span></span></div><p className="field-description">{mode === "prd" ? "Add at least one screenshot or screen recording to show your product accurately." : "Screenshots, product recordings, or your logo. The closer to your product, the better."}</p><UploadField kind="asset" files={assets} onChange={setAssets} limits={session.limits} otherFiles={[...prdFiles, ...referenceFiles]} disabled={busy}/></div>
      </section>
      <section className="form-section"><div className="form-section-heading"><span className="step-number">02</span><div><h2>Choose the occasion</h2><p>A big introduction or a closer look.</p></div></div><fieldset className="video-type-grid" disabled={busy}><legend className="visually-hidden">Video type</legend><label className={`choice-card${videoType === "launch" ? " selected" : ""}`}><input type="radio" name="videoType" value="launch" checked={videoType === "launch"} onChange={() => setVideoType("launch")}/><span className="choice-card-top"><Clapperboard size={21} strokeWidth={1.5}/><span className="choice-radio">{videoType === "launch" && <Check size={11} strokeWidth={3}/>}</span></span><strong>Product launch</strong><span>Introduce what you built<br/>and why it matters.</span></label><label className={`choice-card${videoType === "feature-demo" ? " selected" : ""}`}><input type="radio" name="videoType" value="feature-demo" checked={videoType === "feature-demo"} onChange={() => setVideoType("feature-demo")}/><span className="choice-card-top"><MousePointer2 size={21} strokeWidth={1.5}/><span className="choice-radio">{videoType === "feature-demo" && <Check size={11} strokeWidth={3}/>}</span></span><strong>Feature demo</strong><span>Make one great capability<br/>easy to understand.</span></label></fieldset>{videoType === "feature-demo" && <p className="field-hint demo-hint">For an in-app workflow, include screenshots or a recording showing that feature in use.</p>}</section>
      <section className="form-section"><div className="form-section-heading"><span className="step-number">03</span><div><h2>Make it yours</h2><p>A little direction, if you have something in mind.</p></div></div><details className="reference-details"><summary><span><Layers3 size={18}/><strong>Add a style reference</strong><span className="optional-note">Optional</span></span><ChevronDown size={17}/></summary><div className="reference-body"><p className="field-description">Share a video for pacing, typography, and mood. Its footage and audio won’t appear in your video.</p><fieldset className="segmented-control reference-control" disabled={busy}><legend className="visually-hidden">Reference source</legend><label className={referenceMode === "upload" ? "selected" : ""}><input type="radio" name="referenceMode" checked={referenceMode === "upload"} onChange={() => setReferenceMode("upload")}/>Upload a video</label><label className={referenceMode === "link" ? "selected" : ""}><input type="radio" name="referenceMode" checked={referenceMode === "link"} onChange={() => setReferenceMode("link")}/>Public video link</label></fieldset>{referenceMode === "upload" ? <UploadField kind="reference" files={reference} onChange={setReference} limits={session.limits} otherFiles={[...prdFiles, ...assets]} disabled={busy}/> : <div><label htmlFor="reference-url">Direct public video URL</label><div className="input-with-icon"><Link2 size={17}/><input id="reference-url" type="url" value={referenceUrl} onChange={(event) => setReferenceUrl(event.target.value)} placeholder="https://example.com/reference.mp4" disabled={busy}/></div><p className="field-hint">Use a direct MP4, MOV, or WebM link. For social or video-sharing posts, upload a video file you have permission to use.</p></div>}</div></details>
        <fieldset className="format-field" disabled={busy}><legend>Output format</legend><div className="format-grid">{formats.map(({ value, label, detail, icon: Icon }) => <label key={value} className={`format-choice${format === value ? " selected" : ""}`}><input type="radio" name="format" value={value} checked={format === value} onChange={() => setFormat(value)}/><Icon size={21} strokeWidth={1.5}/><strong>{label}</strong><span>{detail}</span></label>)}</div><p className="field-hint">Auto follows your reference’s shape, or uses landscape without one.</p></fieldset>
      </section>
      <div className="form-submit-section">{error && <div ref={errorBox} className="notice notice-error" role="alert" tabIndex={-1}><div><strong>We couldn’t start this video.</strong><p>{error}</p></div></div>}<button type="submit" className="button button-primary generate-button" disabled={!canSubmit}>{busy ? <><LoaderCircle size={18} className="spin"/> Starting your video…</> : uploading ? <><LoaderCircle size={18} className="spin"/> Uploading your files…</> : <>Create video <ArrowRight size={18}/></>}</button><p className="submission-caption">{failedUpload ? "Remove or upload failed files again before continuing." : missingSource ? mode === "url" ? "Add your product URL to get started." : "Add a product brief and at least one visual to get started." : <><LockKeyhole size={12}/> Your inputs and finished video stay private.</>}</p></div>
    </form><aside className="creation-aside"><div className="creative-card"><div className="creative-card-label"><span className="mini-brand-mark">▶</span> Made for your next release</div><FilmArtwork compact/><div className="creative-card-copy"><h2>A good product<br/>deserves a great entrance.</h2><p>Real product visuals. Thoughtful motion.<br/>A story that brings it all together.</p></div></div><div className="included-card"><span className="eyebrow">The finishing touches, included</span><div><span className="included-icon"><Monitor size={18}/></span><p><strong>Your product, clearly shown</strong><span>Actual screenshots and supplied recordings.</span></p></div><div><span className="included-icon"><Sparkles size={18}/></span><p><strong>A little motion, a lot of intention</strong><span>Typography and transitions with purpose.</span></p></div><div><span className="included-icon"><AudioLines size={18}/></span><p><strong>Sound that sets the mood</strong><span>Instrumental music and selective sound effects.</span></p></div><div className="included-footnote"><Check size={15}/><span>A finished MP4, checked before delivery.</span></div></div><div className="beta-limits"><span>Good to know</span><p>Up to {session.limits.maxFiles} files and {formatBytes(session.limits.maxTotalBytes)} per submission. Your beta includes up to {session.limits.maxJobsPerDay} videos each day.</p><a href="/studio/guide">Before your first video <ArrowUpRight size={13}/></a></div></aside></div>
  </>;
}
